### PR TITLE
Update ArticleController

### PR DESCRIPTION
**Pull request by ericlima**
at line 137 corrected the return of that shows 10.000,00 and the correct is 100,00%

### CODE REVIEW

**Comment by rootpd** [comment]
This was actually intentional. The conversion rates are usually low for articles and we didn't wanted display unnecessary leading zeros to the editorial staff.

It's actually explained in tooltip as well.

image

If the exact percentage is something you need to display, we'll probably need to change this to make that multiplier configurable first. By default, it would display the exact percentage as you proposed, but anyone would still be able to multiply it as needed.

**Comment by rootpd** [comment]
The internal reference is `remp/remp#475`

**Comment by ericlima** [comment]
Screenshot from 2019-08-09 16-38-46
BUT.... the number showed is wrong masked, and when I try to put a mask on that column. It shows ( NaN% ), because the column is converted in String at controller.

**Comment by ericlima** [comment]
and on Article Information page the rate is Zero (should be 100%)
Screenshot from 2019-08-09 16-59-20

**Comment by ericlima** [comment]
in dashboard the conversion rate is wrong also.

Screenshot from 2019-08-09 17-01-47

**Comment by rootpd** [comment]
This was handled within https://github.com/remp2020/remp/commit/78b31f259feb65743feecabc163fdf4a63537f5c by more complex solution. Description at https://github.com/remp2020/remp/pull/22#issuecomment-527420074

**Pull request closed without merging**
