### PR TITLE
datatables sharing

### PR DESCRIPTION
**Pull request by kudlohlavec**
datatables - tweaking of state callbacks in order to save and load state by url parameters

datatables - applying code review hints

### CODE REVIEW

**Comment by kudlohlavec** [comment]
> * [ ]  Can we make rison state in url **not** base64 encoded? The URL looks really ugly and it's not possible to read any settings from it.

It is not being encoded by base64. You have probably not rebuilt the remp package and tested the older version. Try running `yarn upgrade remp` and `yarn run watch` inside desired subproject.

> * [ ]  When I get to the page with datatable, the initial state should not be converted to the long settings in the URL. It's the default, no need to have that in URL.

Sure, this is the way the datatables package behaves natively - to save its state also in the beginning. But I think it can be altered.

> * [ ]  The amount of data is overwhelming and possibly unnecessary as the only two things that could happen there is ordering and searching.

> So I'd probably try to go with something a bit proprietary, where we would extract:
> 
> * `search` term for columns where search is happening (in the example it's the column with number `4` being searched
> * `order` (if it's different than the default)
> * global `search` term
> * `start` and `length` (to properly indicate page)

My intention was to make it robust towards future changes and additions of new filters (also the unknown ones that can be added in new versions of datatables). By this approach it is not necessary to track every type of filter one by one. However, if length and readability of url is of an importance in here, I can understand your suggestion and will incorporate only partial storage of state parameters.
 
> The rest is just configuration that really doesn't need to be part of the shared URL. However I'm not sure how datatables would behave in restore callback if we'd store only part of the state object.

I will try if it will work with partial object as well. If not, I will probably use dual approach where I will store whole object in local storage and tracked changes will be held in shareable url as well and during loading phase these objects will be combined appropriately.

**Comment by rootpd** [comment]
Changes sound good, I'll take a look again on whether I really had the latest version or not (due to encoding).. Now when I'm thinking about it, it might have been only urlencoded (not base64 encoded).

The "empty default" is probably not necessary. Now when I looked at the Beam's dashboard (where we already use Rison), there were two important things I noticed:

* The default is there already with settings (that's why I just said it's not really necessary)
* The settings are stored as URL fragment (maybe that's why it's not url encoded). If possible, please do it similarly. See the screenshot below and Beam's dashboard implementation (most importantly [here](https://github.com/remp2020/remp/blob/master/Beam/resources/assets/js/components/dashboard/store.js).

image

**Comment by kudlohlavec** [comment]
All PR requests have been incorporated. Please have a look at latest commits.

Regarding working with partial state object, datatables is fine with it so no extra workarounds with dual usage of local storage and url were necessary.

State object was indeed being url encoded, so i also fixed that issue.

Few things to consider in the future:
- if length and readability of url is of high priority, it would be good to look for other ways how to identify specific table. Currently, table id is being used, which is often longer then the partial state itself. For example some kind of html data attribute can be used that will contain shorter unique string etc.
- current approach will be probably producing unknown behaviors when column re-ordering or overall table structure change will occur after generating of url. One solution can be in usage of aria-label column attributes, what will also result in better readability of state parameter in the url, but on the other hand it will result in longer url parameter

**Comment by nakashu** [comment]
I'll add some examples to the point about future above.

```
// current state of stare 
7c4f73101154391b97683d193e42f2ce_state=(length:10,order:!(!(0,desc)),start:0)

// by using some attribute on table itself we can have nice human readable table names
<table class="data-table" data-table-name="scheduled">

// this would result in url: (with some fallback if missing)
scheduled=(length:10,order:!(!(0,desc)),start:0)
```

the second point is relevant to the order/search parameters where the query is constructed using order of columns used.
When new columns will be added or existing rearranged, past urls will return different results as before, thus breaking long term shareability / breadcrumbing
Solution would be to map it to keys/string - from the aria-label html attribute of each column 

```
<th aria-label=created-at>
// the thing could look like
scheduled=(length:10,order:!(!(created-at,desc)),start:0)
// or with multiple with names instead of indexes
scheduled=(length:10,order:!(!(created-at,desc),(name, asc)),start:0)
```

**Comment by rootpd** [comment]
Thanks for the update, looks great! To your points:

* Labeling tables seems like a reasonable idea, but it would only make sense if we started enforcing it now for all tables; which we don't want to. If the length will be an issue, we'll start generating shorted ids to get the same result without forcing developer to think about table naming :). We are aware of situation that the already shared URLs will stop working after the change.

* Column adding/removal is so rare event, that even if that happens, we wouldn't care that some shared links break. Most of the links people share around are "consumed" within couple of minutes. It would however make the URLs a bit more readable. If it would take more than two hours for you to handle, just leave it be.

**Comment by rootpd** [comment]
The rest looks good, so once you confirm whether it makes sense to map the columns based on their label, I'll either wait for the implementation or merge it.

Please also squash your commits before we merge it, otherwise github wouldn't be able to recognize the merge after we do it in our private repository (this repo is only the mirror). Thanks.

**Comment by kudlohlavec** [comment]
I would leave it as it is right now, without tracking of column labels. I have already rebased this branch on master and commits were also already squashed so let me now if there is some problem with commits, otherwise feel free to merge 😉

**Pull request merged**
