### PR TITLE
Article metrics visualization

### PR DESCRIPTION
**Pull request by matejminar**

### CODE REVIEW

**Comment by rootpd** [comment]
Found (probably) an edge case issue causing JS error. Attached video here: https://drive.google.com/file/d/1hUvMWMqQcUIUakWhZVm0-uErcvffoJLE/view?usp=sharing

**Comment by rootpd** [comment]
Code-wise it _looks_ OK to me. There's some weird reading progress data coming from our side, but the component itself looks OK.

**Comment by matejminar** [comment]
Thanks for the feedback.
I've added functionality to always show histogram, created new vue component for "question mark tooltips" and handled case when no count_histogram array is present in response from `/api/journal/pageviews/actions/progress/count`

**Comment by rootpd** [comment]
The size of generated JS has risen from ~630KB to 2.5M. That's a significant raise considering the amount of features implmemented here. Any idea what could have caused it?

**Comment by matejminar** [comment]
Yes, we added vuetify ui library (the same one is used in segmenter) to use their tooltips.
My bad, I was under the impression that if I import tooltips like this:
```
import { VTooltip } from "vuetify/lib";
```
only tooltips get imported without the bloat of entire component library.
It's their `a-la-carte` option of importing stuff where treeshaking should work:
https://vuetifyjs.com/en/customization/a-la-carte

I can take a look and try to optimize / use something different.

**Comment by rootpd** [comment]
Ouch, 2M is probably too much just for the tooltips. There might be a way how to tell webpack to treeshake the rest but I'm not aware of that.

We can go with something smaller.. https://akryum.github.io/v-tooltip/#/ maybe?

**Comment by matejminar** [comment]
Oh, I see the problem. 
Treeshaking works only in production build (`npm run iota-production`) which gets us to total size of 217KB for entire iota.js (198KB without tooltips).
Is that acceptable, or should I take a look at akryum's v-tooltip?

**Comment by rootpd** [comment]
Ooooh. In that case we're fine. :)

**Comment by rootpd** [comment]
I've merged squashed commit into master, closing this up/

**Pull request closed without merging**
